# Generated by Django 2.1.5 on 2019-02-10 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('student_number', models.CharField(max_length=10)),
                ('birthday', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('email', models.CharField(default=None, max_length=50)),
                ('github', models.URLField(default=None)),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', '---')], default='X', max_length=1)),
            ],
        ),
    ]
